apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quqk
    app.kubernetes.io/part-of: byoc-app-gkrk
  name: quqk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quqk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quqk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-kjsl-tenant/byoc-app-gkrk/quqk@sha256:9bc93575494a6308695da33175ac7a09b2755c8bf55d934bdf551add6df0a091
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
