apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quqk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quqk
    app.kubernetes.io/part-of: byoc-app-gkrk
  name: quqkyegk
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: quqk
    weight: null
status: {}
